MMS Client Router
The MMS cloud router is simple solution for integration of the Java based MMS client with non-Java based platforms.

The router simply translate REST based messages to and from MMS messages:

C++/C# -> REST -> MMS Router -> MMS protocol -> MMS server -> MMS protocol -> MMS Client

The REST format that is exchanged between C++/C# clients is the JSON representation of the message
as defined by its MSDL file. 

There are 6 main endpoints to access the Maritime Messing Service
  /mms/broadcast/send   : Used for sending broadcasts
  /mms/broadcast/listen : Used for listening for broadcast
  /mms/service/register : USed for registering a service
  /mms/service/invoke   : Used for invoking a service
  /mms/service/find     : Used for finding a service
  /mms/position/report  : Used for reporting the current position to MMS Server
  
=== Endpoint Details

  
==== Broadcast Listen
Used for listening for specific broadcast messages. The main idea is to specify a HTTP URL that the MMS router will invoke every time it receives a broadcast message from
the server.
parameters:
    1: Comma separated list of the names of each broadcast message to listen to;
    2: The area to listen in, should only be used by stationary actors (Optional).
    3: A callback back URL (http://10.0.0.123/xyz) that will be invoked with each received message

==== Position Report
Should be invoked every second with the latest position.
The MMS Router will decide when to publish updates to MMS server.


=== Starting the router

> maritimecloudrouter.sh -DmaritimeId=139232829 -Dformat=JSON -Dserver=mms.maritimecloud.net -localport=12392