== Maritime Service Definition Language


In the following sections we will

=== Background

==== Issues with AIS

==== XML and every bit counts.


===
Der skal vaere struktur.



=== Units

Security


The Mars Climate Orbiter (formerly the Mars Surveyor '98 Orbiter) was a 338 kilogram (750 lb) robotic space probe launched by NASA on December 11, 1998 to study the Martian climate, atmosphere, and surface changes and to act as the communications relay in the Mars Surveyor '98 program for Mars Polar Lander. However, on September 23, 1999, communication with the spacecraft was lost as the spacecraft went into orbital insertion, due to ground-based computer software which produced output in non-SI units of pound-seconds (lbf×s) instead of the metric units of newton-seconds (N×s) specified in the contract between NASA and Lockheed. The spacecraft encountered Mars on a trajectory that brought it too close to the planet, causing it to pass through the upper atmosphere and disintegrate.[1][2]

http://en.wikipedia.org/wiki/Gimli_Glider


Confusion over units during the process of metrication can sometimes lead to accidents. One of the most notable examples was during metrication in Canada. In 1983, an Air Canada Boeing 767, nicknamed the "Gimli Glider" following the incident, ran out of fuel in midflight. The incident was caused, in a large part, by the confusion over the conversion between litres, kilograms, and pounds, resulting in the aircraft receiving 22,300 pounds of fuel instead of the required 22,300 kg.[74]

http://en.wikipedia.org/wiki/Gimli_Glider


To avoid such problems. 